# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vehicle_type', models.IntegerField()),
            ],
        ),
    ]
