# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='default_val', max_length=100),
            preserve_default=False,
        ),
    ]
